name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Step runs
        id: running-step
        run: echo Hello, world!

      - name: Step fails
        run: echo fails && exit 1
        
      - name: Step runs always
        if: always()
        run: echo runs always
        
      - name: Step could run
        if: ${{ always() && steps.running-step.outcome == 'success' }}
        run: echo runned

      - name: Step could run
        if: ${{ always() && steps.running-step.outcome == 'failure' }}
        run: echo runned
        
      - name: Step could run
        if: ${{ !cancelled() }}
        run: exit 1

      - name: Step could run
        if: ${{ !cancelled() && steps.running-step.outcome == 'success' }}
        run: echo runned
        
      - name: Step could run
        if: ${{ !cancelled() && steps.running-step.outcome == 'failure' }}
        run: echo runned
