name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-job:
    name: On PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: -1

      - name: github.event.pull_request.base.sha
        id: running-step
        run: |
          git fetch
          git branch -a
          echo ${{ github.base_ref }}
          echo ${{ github.event.pull_request.base.sha }}
          ls -lha
          git log -1 ${{ github.event.pull_request.base.sha }}
          git show remotes/origin/${{ github.event.pull_request.base.sha }}:text.txt
          git show remotes/origin/main:text.txt
          

      - name: Step fails
        run: echo fails && exit 1
        
      - name: Step always
        if: always()
        run: echo runs always
        
      - name: Step always + outcome.success
        if: ${{ always() && steps.running-step.outcome == 'success' }}
        run: echo runned

      - name: Step always + outcome.failure
        if: ${{ always() && steps.running-step.outcome == 'failure' }}
        run: echo runned
        
      - name: Step !cancelled
        if: ${{ !cancelled() }}
        run: echo runned

      - name: Step !cancelled + outcome.success
        if: ${{ !cancelled() && steps.running-step.outcome == 'success' }}
        run: echo runned
        
      - name: Step !cancelled + outcome.failure
        if: ${{ !cancelled() && steps.running-step.outcome == 'failure' }}
        run: echo runned

      - name: Step without condition
        run: echo Bye, Bye!
